CREATE TABLE squid_logs (
  idsquid_logs INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  DATA_ACESSO DATE NOT NULL,
  HORA TIMESTAMP NOT NULL,
  IP VARCHAR(18) NOT NULL,
  URL TEXT NOT NULL,
  T_RESPOSTA INTEGER UNSIGNED NULL,
  STATUS_ACESSO VARCHAR(30) NULL,
  BYTES_TRANSFER INTEGER UNSIGNED NULL,
  METODO_DE_TRANSFERENCIA VARCHAR(20) NULL,
  CACHE VARCHAR(64) NULL,
  TIPO_DE_OBJETO VARCHAR(20) NULL,
  PRIMARY KEY(idsquid_logs, DATA_ACESSO, HORA, IP, URL)
);


